git checkout test_buffer buffer_specified.xml
git checkout test_buffer buffer_unspecified.xml
git checkout test_buffer mux_specified.xml
git checkout test_buffer mux_unspecified.xml
git checkout test_buffer mux_specified_tot.xml
git checkout test_buffer mux_unspecified_tot.xml
git checkout test_buffer mux_specified_in.xml
git checkout test_buffer mux_unspecified_in.xml
git checkout test_buffer mux_specified_out.xml
git checkout test_buffer mux_unspecified_out.xml
git checkout test_buffer pass_specified.xml
git checkout test_buffer pass_unspecified.xml
git checkout test_buffer short_specified.xml
git checkout test_buffer short_unspecified.xml
git checkout test_buffer tri_specified.xml
git checkout test_buffer tri_unspecified.xml
git checkout test_buffer tri_unspecified_tot.xml
git checkout test_buffer tri_specified_tot.xml
git checkout test_buffer tri_specified_in.xml
git checkout test_buffer tri_unspecified_in.xml
git checkout test_buffer tri_specified_out.xml
git checkout test_buffer tri_unspecified_out.xml
